config/routes.rb
Comissoes::Application.routes.draw do
  LOCALES = /en|pt\-BR/
  scope "(:locale)", :locale => LOCALES do
    resources :products
    resources :clients
    resources :symptoms
    resources :users
    resource  :profile
    resource  :confirmation, :only => [:show]
    resource  :user_sessions, :only => [:create, :new, :destroy]
  end

  match '/:locale' => 'home#index', :locale => LOCALES
  root :to => "home#index"
end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
  # GET /symptoms
  # GET /symptoms.json
  def index
    @symptoms = Symptom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @symptoms }
    end
  end

  # GET /symptoms/1
  # GET /symptoms/1.json
  def show
    @symptom = Symptom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @symptom }
    end
  end

  # GET /symptoms/new
  # GET /symptoms/new.json
  def new
    @symptom = Symptom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @symptom }
    end
  end

  # GET /symptoms/1/edit
  def edit
    @symptom = Symptom.find(params[:id])
  end

  # POST /symptoms
  # POST /symptoms.json
  def create
    @symptom = Symptom.new(params[:symptom])

    respond_to do |format|
      if @symptom.save
        format.html { redirect_to @symptom, notice: 'Symptom was successfully created.' }
        format.json { render json: @symptom, status: :created, location: @symptom }
      else
        format.html { render action: "new" }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /symptoms/1
  # PUT /symptoms/1.json
  def update
    @symptom = Symptom.find(params[:id])

    respond_to do |format|
      if @symptom.update_attributes(params[:symptom])
        format.html { redirect_to @symptom, notice: 'Symptom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /symptoms/1
  # DELETE /symptoms/1.json
  def destroy
    @symptom = Symptom.find(params[:id])
    @symptom.destroy

    respond_to do |format|
      format.html { redirect_to symptoms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/views/symptoms/_form.html.erb
<%= simple_form_for(@symptom) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/symptoms/edit.html.erb
<h1>Editing symptom</h1>

<%= render 'form' %>

<%= link_to 'Show', @symptom %> |
<%= link_to 'Back', symptoms_path %>

app/views/symptoms/index.html.erb
<h1>Listing symptoms</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @symptoms.each do |symptom| %>
  <tr>
    <td><%= symptom.name %></td>
    <td><%= link_to 'Show', symptom %></td>
    <td><%= link_to 'Edit', edit_symptom_path(symptom) %></td>
    <td><%= link_to 'Destroy', symptom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Symptom', new_symptom_path %>

app/views/symptoms/new.html.erb
<h1>New symptom</h1>

<%= render 'form' %>

<%= link_to 'Back', symptoms_path %>

app/views/symptoms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @symptom.name %>
</p>


<%= link_to 'Edit', edit_symptom_path(@symptom) %> |
<%= link_to 'Back', symptoms_path %>