config/routes.rb
Comissoes::Application.routes.draw do
  LOCALES = /en|pt\-BR/
  scope "(:locale)", :locale => LOCALES do
    resources :products
    resources :clients
    resources :symptoms
    resources :users
    resource  :profile
    resource  :confirmation, :only => [:show]
    resource  :user_sessions, :only => [:create, :new, :destroy]
  end

  match '/:locale' => 'home#index', :locale => LOCALES
  root :to => "home#index"
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :consultant, :indicator, :name, :cpf, :address, :neighborhood, :city, :stade, :zip
  validates_presence_of :name, :cpf, :address, :neighborhood, :city, :stade, :zip
  validates_uniqueness_of :name
  usar_como_cpf :cpf
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :require_authentication

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(params[:client])

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @client = Client.find(params[:id])

    if @client.update_attributes(params[:client])
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    redirect_to clients_url
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :cpf %>
    <%= f.input :address %>
    <%= f.input :neighborhood %>
    <%= f.input :city %>
    <%= f.input :stade %>
    <%= f.input :zip %>
    <%= f.input :consultant, :wrapper => :inline_checkbox %>
    <%= f.input :indicator, :wrapper => :inline_checkbox %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "create" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @client, :class => "btn" %>
<%= link_to t('links.back'), clients_path, :class => "btn" %>

app/views/clients/index.html.erb
<h1>Lista de Clientes</h1>

<table class="table table-bordered table-striped table-hover">
  <tr>
    <th><%= Client.human_attribute_name(:name) %></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td style="width: 78%"><%= client.name %></td>
    <td >
      <%= link_to content_tag('i', '', :class => 'icon-shopping-cart') + " Vendas", client, :class => 'btn btn-mini'%>
      <%= link_to content_tag('i', '', :class => 'icon-eye-open'), client, :class => 'btn btn-mini'%>
      <%= link_to content_tag('i', '', :class => 'icon-pencil'), edit_client_path(client), :class => 'btn btn-mini' %>
      <%= link_to content_tag('i', '', :class => 'icon-remove icon-white'), client, method: :delete, data: { confirm: 'Confirme exclusão?' }, :class => 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('links.new', :model => 'Cliente'), new_client_path, :class => 'btn' %>

app/views/clients/new.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form' %>
<%= link_to t('links.back'), clients_path, :class => "btn" %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Consultant:</b>
  <%= @client.consultant %>
</p>

<p>
  <b>Indicator:</b>
  <%= @client.indicator %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>