config/routes.rb
Comissoes::Application.routes.draw do
  LOCALES = /en|pt\-BR/
  scope "(:locale)", :locale => LOCALES do
    resources :products
    resources :clients
    resources :symptoms
    resources :users
    resource  :profile
    resource  :confirmation, :only => [:show]
    resource  :user_sessions, :only => [:create, :new, :destroy]
  end

  match '/:locale' => 'home#index', :locale => LOCALES
  root :to => "home#index"
end

app/views/layouts/_user_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><%= link_to 'Home', root_path %></li>
          <li class=""><%= link_to t('layout.clients'), clients_path %></li>
          <li class=""><%= link_to t('layout.products'), products_path %></li>
          <li class=""><%= link_to t('layout.my_profile'), user_path(current_user) %></li>
          <li class=""><%= link_to t('layout.signout'), user_sessions_path, :method => :delete %></li>
        </ul>
        <form class="navbar-search pull-right dropdown">
          <input id="searchText" type="search" class="search-query dropdown-toggle" placeholder="Buscar" autocomplete="off">
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_visitor_navbar.html.erb
<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
<div class="nav-collapse collapse">
  <ul class="nav">
    <li class="home-menu active"><%= link_to 'Home', root_path %></li>
    <li class="users-menu"><%= link_to t('layout.clients'), clients_path %></li>
    <li class="products-menu"><%= link_to t('layout.products'), products_path %></li>
    <li class="users-menu"><%= link_to t('layout.users'), users_path %></li>
    <li class="symptoms-menu"><%= link_to 'Sintomas', '' %></li>
    <li class="symptoms-menu"><%= link_to t('layout.signup'), new_user_path %></li>
    <li class="symptoms-menu"><%= link_to t('layout.signin'), new_user_sessions_path %></li>
  </ul>
  <form class="navbar-search pull-right dropdown">
    <input id="searchText" type="search" class="search-query dropdown-toggle" placeholder="Buscar" autocomplete="off">
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comissoes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    <%= render 'layouts/user_navbar' %>
  <% end %>

  <div class="container">
    <br/>
    <div class="row-fluid">
      <div class="span12" id="content">
        <%= yield %>
      </div>
    </div>
    <hr>
    <footer>
      <p>&copy; Sistema de Comissões 2013.
    </footer>
  </div>

</body>
</html>